# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do

  desc "Create ipa"
  lane :build do |options|
 	latest_build_number = latest_testflight_build_number + 1
	increment_build_number(
   		build_number: latest_build_number,
                xcodeproj: "One Space.xcodeproj"
	)
	configuration = (options[:env] == "STG" ? "STG" : options[:env] == "DEV" ? "DEV" : "PROD")
	gym(workspace: "One Space.xcworkspace", scheme: "One Space", configuration: configuration)
	notification(subtitle: "#{configuration} build was finished ", message: "Build number #{latest_build_number} was completed...")
	latest_build_number
  end

  desc "Create ipa, Upload to TestFlight"
  lane :upload do |options|
    latest_build_number = build(options)
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "wtiq-ofgi-llnx-pbkd"
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    upload_to_testflight(skip_waiting_for_build_processing: true)
    env_value = (options[:env] == "STG" ? "STG" : options[:env] == "DEV" ? "DEV" : "PROD")
    #notify_via_telegram(number_value: latest_build_number, env_value: env_value)
    notification(subtitle: "Upload was finished ", message: "Uploading completed...")
  end

  desc "Notify via Telegram"
  lane :notify_via_telegram do |options|
      telegram(
      token: "719983411:AAGNgcOz5511Ce5mzTs9z-yQKjloEau3vls",
      chat_id: "453374142",
      text: "New iOS build number: #{options[:number_value]} for #{options[:env_value]} environment will be available in the TestFlight in 15 minutes"
    )
  end

   error do |lane, exception|
    # This block is called, if there was an error running a specific lane.
  end

end
